pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()

        // [required] revup library
        // 미러링/그룹 저장소라 네트워크별 저장소를 따로 잡을 필요가 없다.
        maven {
            url "https://repository.tnkad.net/repository/public/"
        }
    }
}

include(':app')