apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    defaultConfig {
        manifestPlaceholders = [
                adiscope_media_id: "media id 기입필요",
                adiscope_media_secret: "media secret 기입필요",
                adiscope_sub_domain: "" // 옵션값(오퍼월 상세페이지 이동 기능)으로 사용 시 value에 전달값을 기입
        ]

        applicationId "com.nps.sample"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        debug {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    Dependency revupBom = platform("com.tnkfactory.revup:revup-bom:5.4.0")
    implementation revupBom

    // [required] revup core library
    implementation "com.tnkfactory.revup:revupCore"
    implementation "com.tnkfactory.revup:revupAndroid"

    // [optional] revup video simple integration library
    implementation "com.tnkfactory.revup:revupWalnut"

    // [optional] revup network adapter library
    // bidding, waterfall adapter
    implementation "com.tnkfactory.revup:adapter.admob"

    // bidding adapter
    implementation "com.tnkfactory.revup:adapter.max"

    // waterfall adapter
    implementation "com.tnkfactory.revup:adapter.chartboost"
    implementation "com.tnkfactory.revup:adapter.pangle"
    implementation "com.tnkfactory.revup:adapter.vungle"

    // direct sold adapter
    implementation "com.tnkfactory.revup:adapter.tnkpub"
}
